title: luzhishen
description: My Personal Blog
author: luzhishen
logo: /wittyLuzhishen.github.io/static/img/avatar.png
github: https://github.com/wittyLuzhishen
about: µãµãµÎµÎ

baseurl: "https://wittyluzhishen.github.io/"
url: "https://wittyluzhishen.github.io/"

disqus_shortname: luzhishen
google_analytics: UA-72862926-1


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
